SELECT B.ANIMAL_ID
     , B.NAME
  FROM ANIMAL_INS A, ANIMAL_OUTS B
 WHERE A.ANIMAL_ID(+) = B.ANIMAL_ID -- RIGHT JOIN(입양 테이블 기준)
   AND A.ANIMAL_ID IS NULL -- 입양간 기록은 있으나 보호소 들어온 ID가 없는 동물
 ORDER BY B.ANIMAL_ID