SELECT A.PRODUCT_CODE
     , SUM(A.PRICE * B.SALES_AMOUNT) AS SALES -- ID가 중복된 행(날짜가 다른 경우) 판매액 모두 합하기 
  FROM PRODUCT A, OFFLINE_SALE B
 WHERE A.PRODUCT_ID = B.PRODUCT_ID
 GROUP BY A.PRODUCT_CODE -- 판매 테이블에서 중복된 ID 존재하므로 묶기
 ORDER BY SALES DESC, A.PRODUCT_CODE