  SELECT WAREHOUSE_ID
       , WAREHOUSE_NAME
       , ADDRESS
       , NVL(FREEZER_YN, 'N') AS FREEZER_YN -- FREEZER_YN 컬럼이 NULL일 때 'N' 출력
    FROM FOOD_WAREHOUSE
   WHERE ADDRESS LIKE '경기도%' -- 주소가 경기도
ORDER BY WAREHOUSE_ID