  SELECT BOOK_ID
       , TO_CHAR(PUBLISHED_DATE, 'YYYY-MM-DD') PUBLISHED_DATE
    FROM BOOK
   WHERE TO_CHAR(PUBLISHED_DATE, 'YYYY') = '2021' -- 2021년 출판
     AND CATEGORY = '인문'
ORDER BY PUBLISHED_DATE