-- TODO 포맷함수 사용하기
SELECT MEMBER_ID
     , MEMBER_NAME
     , GENDER
     , TO_CHAR(DATE_OF_BIRTH, 'YYYY-MM-DD')
  FROM MEMBER_PROFILE
 WHERE GENDER = 'W'
   AND TO_CHAR(DATE_OF_BIRTH, 'MM') = '03' -- 생일이 3월 
   AND TLNO IS NOT NULL -- 전화번호 없는 회원
ORDER BY MEMBER_ID